#!/usr/bin/sh

if [ "$#" -ne 2 ]
then
    echo "Usage: docker-test DIR_WITH_DOCKERFILE TAGGED_IMAGE"
    exit 1
fi

echo "FROM $2" > _Dockerfile.test &&
cat "$1/Dockerfile.test" >> _Dockerfile.test &&
docker build -t "$2-test" -f _Dockerfile.test "$1" &&
docker run --rm -it "$2-test"

rm _Dockerfile.test
