---
- name: Create directories for the server
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ app_base_path }}"
    - "{{ app_base_path }}/data"

- name: Touch visithist
  file:
    path: "{{ app_base_path }}/data/visithist"
    mode: 0666
    state: touch

- name: Copy docker compose YAMLs
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_base_path }}/docker-compose.yml"

- name: Stop previous deployment
  docker_compose:
    project_src: "{{ app_base_path }}"
    state: absent

- name: Run docker compose
  docker_compose:
    pull: true
    project_src: "{{ app_base_path }}"
  register: output

- name: Show docker-compose output
  debug:
    var: output

