---
- name: Create root directory for the server
  file:
    path: "{{ app_base_path }}"
    state: directory

- name: Create data directory for the server
  file:
    path: "{{ app_base_path }}/data"
    state: directory

- name: Copy docker compose YAMLs
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_base_path }}/docker-compose.yml"

- name: Stop previous deployment
  docker_compose:
    project_src: "{{ app_base_path }}"
    state: absent

- name: Run docker compose
  docker_compose:
    project_src: "{{ app_base_path }}"
    pull: true
  register: output

- name: Show docker-compose output
  debug:
    var: output

