---
- name: Install pip and docker compose
  package:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
    state: present

- name: Update pip
  pip:
    name:
      - pip>=20
