---
- name: Deploy docker on VMs
  become: true # Run everything as root
  hosts: pytime_prod
  roles:
    - docker
  tasks:
    - name: Install pip and docker compose
      package:
        name:
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
          - docker-compose
        state: present

    - name: Update pip
      pip:
        name:
          - pip>=20

    - name: Install python dependencies for docker-compose
      pip:
        name:
          - docker
          - pyyaml
          - docker-compose

    - name: Copy docker compose YAMLs
      copy:
        src: files/docker-compose.yml
        dest: /opt/docker-compose.yml

    - name: Run docker compose
      docker_compose:
        project_src: /opt
        files:
        - docker-compose.yml
