---
- name: Deploy docker on VMs
  become: true # Run everything as root
  hosts: pytime_prod
  roles:
    - docker
    - docker_compose
  tasks:
    - name: Copy docker compose YAMLs
      copy:
        src: files/docker-compose.prod.yml
        dest: /opt/docker-compose.yml

    - name: Run docker compose
      docker_compose:
        project_src: /opt
        files:
        - docker-compose.yml
